### ISSUE TITLE
Should `README.md` files in `examples/` have `terraform-docs` injection markers too?

### ISSUE THREAD

**Issue by jsf9k** [cisagov/skeleton-tf-module#192]
# 💡 Summary #

In #189 @mcdonnnj added injection markers to the `README.md` file at the root of the repo.  This allows `terraform-docs` to inject the documentation into the `README.md` file.  Should we also add injection headers to the `README.md` files in the `examples` directory?

## Motivation and context ##

This would make it quicker and easier to touch up the `terraform-docs` documentation in the example code.

**Comment by dav3r** [comment]
> Should we also add injection headers to the README.md files in the examples directory?

I support this.  Can anyone think of a downside to having them in there?

**Comment by mcdonnnj** [comment]
Yes I was just thinking about this the other day but wanted to cross-reference the [config file documentation](https://terraform-docs.io/user-guide/configuration/) to make sure we needed to have a copy. The TL;DR is that we should not need it for modules in the appropriate `modules/` sub-directory, but until functionality is implemented to allow similar behavior for the `examples/` directory we would need to copy or sym-link the configuration file to individual example directories.
