### ISSUE TITLE
Add a script to run `terraform-docs` and repair Markdown headers

### ISSUE THREAD

**Issue by jsf9k** [cisagov/skeleton-tf-module#196]
# 💡 Summary #

We should add a script to this project that
1. Runs `terraform-docs .` from the root directory as well as any necessary submodule or example directories
2. Runs a `sed` command to repair the Markdown headers that `terraform-docs` leaves open

## Motivation and context ##

This would be useful because it would make updating the Terraform documentation as simple as running a single command.

**Comment by mcdonnnj** [comment]
I actually have a branch of `terraform-docs` that adds the ability to output closed ATX headers (our preference) with https://github.com/terraform-docs/terraform-docs/pull/745. If we got traction on that PR and it was merged we would be able to use a `terraform-docs` pre-commit hook after updating configuration files If we wanted to use it in the interim we could update our workflow to install the binary from my fork's branch, add the pre-commit hook, and update configurations in necessary repositories. The only wrinkle is getting the correct version installed on dev machines.
