### ISSUE TITLE
Fix README link to example

### ISSUE THREAD

**Issue by hillaryj** [cisagov/skeleton-tf-module#54]
# 🐛 Summary #

The README link to "Deploy into default VPC" is broken as the file has moved.

Link should direct to `https://github.com/cisagov/skeleton-tf-module/tree/develop/examples/basic_usage` instead of `https://github.com/cisagov/skeleton-tf-module/tree/develop/examples/default_vpc`

## To reproduce ##

1. Click on link in README
1. It bork
1. Big sad

## Expected behavior ##

See useful info!

**Comment by jsf9k** [comment]
Thanks for the issue @hillaryj!

**Comment by hillaryj** [comment]
You're welcome! Sorry for the kraken. 🐙
